Alejandria/settings.py
Alejandria/static/js/navbar.js
books/urls.py
books/views.py

Uslog1 millorar registre

---

Alejandria/settings.py
Alejandria/static/css/swal-forms.css
Alejandria/static/css/sweet-alert.css
Alejandria/static/js/navbar.js
Alejandria/static/js/swal-forms.js
Alejandria/static/js/sweet-alert.js
Alejandria/templates/navbar.html
books/urls.py
books/views.py

Uslog2 millorar login

---

Alejandria/static/css/payment-page/chooseMethod.css
Alejandria/templates/payment.html

S'ha canviat una mica el disseny de la pàgina i ja es pot seleccionar el mètode de pagament: credit card, paypal i net banking.

USBUY6 seleccionar pagament

---

Alejandria/templates/details.html
Alejandria/templates/home.html
books/views.py

details and some bugs

---

Alejandria/templates/search.html
books/views.py

Ara apareix el missatge: There are no results. 
quan un carrousel esta buit.

Fixed empty carrousel

---

Alejandria/static/css/editor-page/card.css
Alejandria/templates/cart.html
Alejandria/templates/editor_library.html
Alejandria/templates/home.html
Alejandria/templates/navbar.html
Alejandria/templates/search.html
books/urls.py
books/views.py

S'ha afegit tota la biblioteca del editor, necessito fer el merge per veure les imatges dels llibres, però per la resta està tot funcional excepte la funcionalitat de:
- Editar
- Eliminar
Que això ho fa algú en un altre tasca i ho haurem de linkar.

editor library added

---

Alejandria/static/js/navbar.js
books/test/test_register.py
books/views.py

Formulari i server side per guardar dades. També test funcionals

Uslog5 formulari recomanacio

---

Alejandria/static/css/cart-page/body.css
Alejandria/static/css/navbar.css
Alejandria/static/css/payment-page/chooseMethod.css
Alejandria/static/js/payment-page/showproducts.js
Alejandria/templates/cart.html
Alejandria/templates/payment.html
books/views.py

Usbuy6 modificar vista pagina

---

.travis.yml
Alejandria/view.py
README.md
api_read_files.py
books/admin.py
books/apps.py
books/backend.py
books/forms.py
books/models.py
books/test/test_models.py
books/views.py
database.py
pylintrc
requirements.txt

Pylint added to the project, also pylint-django and Travis CI configuration for it to test if there is any errors.
Closes #138

Pylint config

---

Alejandria/static/css/card-filtre.css
Alejandria/static/css/card.css
Alejandria/templates/details.html
Alejandria/templates/home.html
Alejandria/templates/search.html
Alejandria/templates/searchresult.html
books/views.py

S'ha implementat un nou carrousel on es poden veure els llibres que fa una setmana que s'han publicat...
També s'ha canviat el disseny del card-body per als carrousels.

Usreco5 recently added books

---

Alejandria/static/css/payment-page/modal.css
Alejandria/static/js/payment-page/modal.js
Alejandria/templates/cart.html
Alejandria/templates/payment.html
books/models.py
books/test/test_cart.py
books/test/test_models.py
books/test/test_register.py
books/test/test_views.py
books/urls.py
books/views.py
database.py

Now you can access the payment page and complete purchase. If all the fields of the form is written in the correct format creates a new model BankAccount for the user (first time purchasing).
The user's data will automatically provide for the next time he purchases.
*** Important: Models are updated. ***
Tests created and passed correctly.
Closes #108

Usbuy6 conectar backend frontend

---

Alejandria/static/css/bill-pdf/template.css
Alejandria/static/js/home-page/modal.js
Alejandria/static/js/payment-page/modal.js
Alejandria/templates/bill_pdf.html
Alejandria/templates/home.html
Alejandria/templates/payment.html
Expenses.pdf
books/models.py
books/test/test_views.py
books/urls.py
books/views.py
database.py
requirements.txt

Al posar les dades en els camps de la pagina de pagament es comproven si estan escrites correctament en cas d'error s'envia un miisatge; en cas d'exit s'efectua la compra i s'envia un missatge. En aquest missatge apareix la opció de descargar un pdf amb els detalls de la compra. També s'envia un mail al usuari destinat.
Close #117 
Close #116 
Close #109

Mostrar factura, enviar mail i validar camps

---

books/test/test_change_profile.py
books/test/test_views.py
books/views.py

Fixing some details in backend and tests.

Fixing some backend details and tests

---

.coveragerc
.coveralls.yml
.travis.yml
README.md
requirements.txt

Files modified to accept the new repository, coveralls working.
Closes #148

Coveralls modified to 

---

Alejandria/templates/details.html
books/models.py
books/urls.py
books/views.py

Fixed reviews problems. Should work now.

Fixed reviews

---

Alejandria/static/css/faq-page/faqs.css
Alejandria/templates/faqs.html
books/views.py

Merging with actual develop

---

Alejandria/templates/user_bills.html
books/urls.py
books/views.py

Download previous bills

---

Alejandria/static/js/navbar.js
books/urls.py
books/views.py

All fields are validated before next step:
- Username and email has real-time validation if they already exists.
- Email Format is  checked.
- Countries are now a dropbox so user can't make mistakes.
- Zip code must be 5 numbers so non-number or 5+ chars are deleted automatically.
- Every other field is checked to not be empty

USLOG1 Form Validation

---

Alejandria/templates/search.html
books/views.py

Translate text + fix recommended books

Fixed search page

---

Alejandria/templates/home.html
books/views.py

Coming soon added

---

Alejandria/templates/details.html
books/forms.py
books/models.py
books/views.py

This issue closes #191 , closes #205, closes #204 and closes #188.
Added buttons for "likes" and "reads" if you are logged.

Db update book properties

---

Alejandria/static/css/editor-page/card.css
Alejandria/templates/desired_library.html
Alejandria/templates/navbar.html
Alejandria/templates/search.html
books/urls.py
books/views.py

Uswish1 llibreria desitjats

---

Alejandria/static/css/cart-page/body.css
Alejandria/static/js/cart-page/register.js
Alejandria/templates/cart.html
Alejandria/templates/delete_book.html
Alejandria/templates/details.html
Alejandria/templates/editor_library.html
Alejandria/templates/sell.html
books/views.py

Fixes done

---

Alejandria/static/js/navbar.js
Alejandria/templates/home.html
Alejandria/templates/navbar.html
books/views.py

Added some buttons to it and scroll when this buttons are clicked.
This pull request closes #225

Improve navbar

---

Alejandria/templates/edit_book.html

fixed discount not showing

---

Alejandria/static/css/about-page/about-us.css
Alejandria/static/js/navbar.js
Alejandria/templates/about_us.html
Alejandria/templates/navbar.html
books/urls.py
books/views.py

About page finished.

---

Alejandria/templates/home.html
books/views.py

Usreco6 completed

---

Alejandria/templates/home.html
Alejandria/templates/navbar.html
books/test/test_book_view.py
books/test/test_buy.py
books/views.py

this pull request fixes some bugs of last hour

Fix styles
